{"name": "test_a", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <test_pytestjob.Test_one object at 0x000002BF9BF5F5F8>\n\n    def test_a(self):\n        print('------我是第一个pytest程序----------')\n>       assert 1==2\nE       assert 1 == 2\n\ntest_pytestjob.py:13: AssertionError"}, "start": 1600330979647, "stop": 1600330979648, "uuid": "e5d6e974-c6c2-4440-b6a6-9088facfa31b", "historyId": "f8a8e317057407b7e4f6cc6b226ebdbe", "testCaseId": "378561f9864041fe9fa859f93933b030", "fullName": "test_pytestjob.Test_one#test_a", "labels": [{"name": "suite", "value": "test_pytestjob"}, {"name": "subSuite", "value": "Test_one"}, {"name": "host", "value": "LAPTOP-CT29F0O2"}, {"name": "thread", "value": "14864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytestjob"}]}